services:
  postgres:
    image: postgres:latest
    container_name: ddd_library_postgres
    environment:

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_network

networks:
  library_network:
    driver: bridge

volumes:
  postgres_data:
