services:
  fastapi:
    container_name: fastapi
    build: ..
    command: uvicorn --factory core.api.main:get_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ..:/code/
    ports:
      - 8000:8000
    networks:
      - backend


networks:
  backend:
    driver: bridge
