"""fix models

Revision ID: 135233902318
Revises: 878248611b8a
Create Date: 2024-08-24 14:11:26.898152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '135233902318'
down_revision: Union[str, None] = '5adcf559fb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_author_id', table_name='book_author')
    op.drop_column('book_author', 'updated_at')
    op.drop_column('book_author', 'id')
    op.drop_column('book_author', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_author', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('book_author', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('book_author', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index('ix_book_author_id', 'book_author', ['id'], unique=False)
    # ### end Alembic commands ###
