"""merge users and book,authors migrations

Revision ID: 5adcf559fb60
Revises:
Create Date: 2024-08-23 23:00:06.068697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adcf559fb60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'authors', 'users', ['creator_id'], ['id'])
    op.add_column('books', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'creator_id')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'creator_id')
    # ### end Alembic commands ###
